name: ExpMiner
main: net.dockter.ExpMiner.ExpMiner
version: 2.0
author: Dockter
platform: BOTH
commands:
  ExpMiner:
    description: Reload config file
    usage: /<command>
softdepend: [PermissionsBukkit]
softdepend: [Permissions]
expminer.use:
        description: Allows you to get EXP from mining
        default: true
expminer.reload:
        description: Reload Configuration
        default: false
