name: ExpMiner
main: net.dockter.expminer.ExpMiner
version: ${version}
author: Dockter
platform: BOTH
commands:
  ExpMiner:
    description: Reload config file
    usage: /<command>
softdepend: [Vault]
expminer.use:
        description: Allows you to get EXP from mining
        default: true
expminer.reload:
        description: Reload Configuration
        default: false
